/**
 * ee_api_data.js
 * Google Earth Engine JavaScript API reference data for auto-completion.
 */

/* Top-level ee.* completions (shown when typing "ee.") */
const EE_TOP_LEVEL = [
  'Algorithms',
  'Array',
  'Classifier',
  'Clusterer',
  'ConfusionMatrix',
  'Date',
  'DateRange',
  'Dictionary',
  'ErrorMargin',
  'Feature',
  'FeatureCollection',
  'Filter',
  'Geometry',
  'Image',
  'ImageCollection',
  'Join',
  'Kernel',
  'List',
  'Number',
  'Projection',
  'Reducer',
  'String',
  'Terrain',
  'apply',
  'batch',
  'call',
  'data',
  'deserialize',
  'initialize',
  'mapchart',
  'serialize',
];

/* ee.Image methods */
const EE_IMAGE_METHODS = [
  'abs',
  'acos',
  'add',
  'addBands',
  'and',
  'aside',
  'asin',
  'atan',
  'atan2',
  'bandNames',
  'bandTypes',
  'bitCount',
  'bitwiseAnd',
  'bitwiseNot',
  'bitwiseOr',
  'bitwiseXor',
  'blend',
  'byte',
  'cast',
  'cbrt',
  'ceil',
  'changeProj',
  'clamp',
  'clip',
  'clipToBoundsAndScale',
  'clipToCollection',
  'connectedComponents',
  'connectedPixelCount',
  'convolve',
  'copyProperties',
  'cos',
  'cosh',
  'date',
  'derivative',
  'distance',
  'divide',
  'double',
  'entropy',
  'eq',
  'expression',
  'float',
  'floor',
  'focal_max',
  'focal_mean',
  'focal_median',
  'focal_min',
  'focal_mode',
  'geometry',
  'glcmTexture',
  'gradient',
  'gt',
  'gte',
  'hsvToRgb',
  'hypot',
  'id',
  'int',
  'int16',
  'int32',
  'int64',
  'int8',
  'interpolate',
  'leftShift',
  'log',
  'log10',
  'long',
  'lt',
  'lte',
  'mask',
  'matrixMultiply',
  'matrixTranspose',
  'max',
  'min',
  'mod',
  'multiply',
  'neighborhoodToBands',
  'neighborhoodToArray',
  'neq',
  'not',
  'or',
  'paint',
  'pixelArea',
  'pixelCoordinates',
  'pixelLonLat',
  'pow',
  'projection',
  'random',
  'randomVisualizer',
  'reduce',
  'reduceConnectedComponents',
  'reduceNeighborhood',
  'reduceRegion',
  'reduceRegions',
  'reduceResolution',
  'reduceToVectors',
  'register',
  'remap',
  'rename',
  'reproject',
  'resample',
  'rgbToHsv',
  'rightShift',
  'round',
  'sample',
  'sampleRegions',
  'select',
  'selfMask',
  'set',
  'setDefaultProjection',
  'setMask',
  'short',
  'signum',
  'sin',
  'sinh',
  'sldStyle',
  'sqrt',
  'stratifiedSample',
  'subtract',
  'tan',
  'tanh',
  'toByte',
  'toDouble',
  'toFloat',
  'toInt',
  'toInt16',
  'toInt32',
  'toInt64',
  'toInt8',
  'toLong',
  'toShort',
  'toUint16',
  'toUint32',
  'toUint8',
  'translate',
  'uint16',
  'uint32',
  'uint8',
  'unmask',
  'unitScale',
  'updateMask',
  'visualize',
  'where',
  'zeroCrossing',
];

/* ee.ImageCollection methods */
const EE_IMAGE_COLLECTION_METHODS = [
  'aggregate_array',
  'aggregate_count',
  'aggregate_count_distinct',
  'aggregate_first',
  'aggregate_histogram',
  'aggregate_max',
  'aggregate_mean',
  'aggregate_min',
  'aggregate_product',
  'aggregate_sample_sd',
  'aggregate_sample_var',
  'aggregate_stats',
  'aggregate_sum',
  'aggregate_total_sd',
  'aggregate_total_var',
  'aside',
  'cast',
  'classify',
  'combine',
  'copyProperties',
  'count',
  'dateRange',
  'distinct',
  'draw',
  'evaluate',
  'filter',
  'filterBounds',
  'filterDate',
  'filterMetadata',
  'first',
  'flatten',
  'geometry',
  'getInfo',
  'getRegion',
  'id',
  'iterate',
  'limit',
  'load',
  'map',
  'max',
  'mean',
  'median',
  'merge',
  'min',
  'mode',
  'mosaic',
  'or',
  'product',
  'qualityMosaic',
  'randomColumn',
  'reduce',
  'reduceColumns',
  'reduceRegion',
  'reduceRegions',
  'reduceToImage',
  'remap',
  'select',
  'set',
  'size',
  'sort',
  'style',
  'sum',
  'toArray',
  'toArrayPerBand',
  'toBands',
  'toList',
  'union',
];

/* ee.Feature methods */
const EE_FEATURE_METHODS = [
  'aside',
  'buffer',
  'bounds',
  'centroid',
  'containedIn',
  'contains',
  'convexHull',
  'copyProperties',
  'difference',
  'disjoint',
  'dissolve',
  'evaluate',
  'geometry',
  'get',
  'getArray',
  'getInfo',
  'getNumber',
  'getString',
  'id',
  'intersection',
  'intersects',
  'isUnbounded',
  'propertyNames',
  'select',
  'set',
  'setGeometry',
  'simplify',
  'symmetricDifference',
  'toDictionary',
  'toGeoJSON',
  'union',
  'withinDistance',
];

/* ee.FeatureCollection methods */
const EE_FEATURE_COLLECTION_METHODS = [
  'aggregate_array',
  'aggregate_count',
  'aggregate_count_distinct',
  'aggregate_first',
  'aggregate_histogram',
  'aggregate_max',
  'aggregate_mean',
  'aggregate_min',
  'aggregate_product',
  'aggregate_sample_sd',
  'aggregate_sample_var',
  'aggregate_stats',
  'aggregate_sum',
  'aggregate_total_sd',
  'aggregate_total_var',
  'aside',
  'bounds',
  'classify',
  'cluster',
  'copyProperties',
  'count',
  'dateRange',
  'difference',
  'distinct',
  'draw',
  'evaluate',
  'filter',
  'filterBounds',
  'filterDate',
  'filterMetadata',
  'first',
  'flatten',
  'geometry',
  'getInfo',
  'id',
  'iterate',
  'inverseDistance',
  'kreige',
  'limit',
  'load',
  'makeArray',
  'map',
  'merge',
  'or',
  'randomColumn',
  'reduceColumns',
  'reduceToImage',
  'remap',
  'select',
  'set',
  'size',
  'sort',
  'style',
  'toArray',
  'toBands',
  'toList',
  'union',
];

/* ee.Geometry methods */
const EE_GEOMETRY_METHODS = [
  'area',
  'aside',
  'bounds',
  'buffer',
  'centroid',
  'containedIn',
  'contains',
  'convexHull',
  'coordinates',
  'coveringGrid',
  'cutLines',
  'difference',
  'disjoint',
  'dissolve',
  'distance',
  'edgesAreGeodesics',
  'evaluate',
  'geodesicArea',
  'getInfo',
  'intersection',
  'intersects',
  'isUnbounded',
  'length',
  'perimeter',
  'projection',
  'serialize',
  'simplify',
  'symmetricDifference',
  'toGeoJSON',
  'toGeoJSONString',
  'transform',
  'type',
  'union',
  'withinDistance',
];

/* ee.Number methods */
const EE_NUMBER_METHODS = [
  'abs',
  'acos',
  'add',
  'and',
  'aside',
  'asin',
  'atan',
  'atan2',
  'bitCount',
  'bitwiseAnd',
  'bitwiseNot',
  'bitwiseOr',
  'bitwiseXor',
  'byte',
  'cbrt',
  'ceil',
  'clamp',
  'cos',
  'cosh',
  'digamma',
  'divide',
  'double',
  'eq',
  'evaluate',
  'exp',
  'float',
  'floor',
  'format',
  'gamma',
  'gammainc',
  'getInfo',
  'gt',
  'gte',
  'hypot',
  'int',
  'int16',
  'int32',
  'int64',
  'int8',
  'leftShift',
  'log',
  'log10',
  'long',
  'lt',
  'lte',
  'max',
  'min',
  'mod',
  'multiply',
  'neq',
  'not',
  'or',
  'parse',
  'pow',
  'rightShift',
  'round',
  'short',
  'signum',
  'sin',
  'sinh',
  'sqrt',
  'subtract',
  'tan',
  'tanh',
  'toByte',
  'toDouble',
  'toFloat',
  'toInt',
  'toInt16',
  'toInt32',
  'toInt64',
  'toInt8',
  'toLong',
  'toShort',
  'toUint16',
  'toUint32',
  'toUint8',
  'trigamma',
  'uint16',
  'uint32',
  'uint8',
];

/* ee.String methods */
const EE_STRING_METHODS = [
  'aside',
  'cat',
  'compareTo',
  'decodeJSON',
  'encodeJSON',
  'evaluate',
  'getInfo',
  'index',
  'length',
  'match',
  'replace',
  'rindex',
  'slice',
  'split',
  'toLowerCase',
  'toUpperCase',
  'trim',
];

/* ee.List methods */
const EE_LIST_METHODS = [
  'add',
  'aside',
  'cat',
  'contains',
  'containsAll',
  'distinct',
  'evaluate',
  'filter',
  'flatten',
  'frequency',
  'get',
  'getInfo',
  'indexOf',
  'indexof',
  'insert',
  'iterate',
  'join',
  'length',
  'map',
  'reduce',
  'remove',
  'removeAll',
  'replace',
  'replaceAll',
  'reverse',
  'rotate',
  'set',
  'size',
  'slice',
  'sort',
  'splice',
  'swap',
  'unzip',
  'zip',
];

/* ee.Dictionary methods */
const EE_DICTIONARY_METHODS = [
  'aside',
  'combine',
  'contains',
  'evaluate',
  'get',
  'getArray',
  'getInfo',
  'getNumber',
  'getString',
  'keys',
  'map',
  'remove',
  'rename',
  'select',
  'set',
  'size',
  'toArray',
  'toDictionary',
  'toImage',
  'values',
];

/* ee.Date methods */
const EE_DATE_METHODS = [
  'advance',
  'aside',
  'difference',
  'evaluate',
  'format',
  'get',
  'getInfo',
  'getRange',
  'millis',
  'unitRatio',
  'update',
];

/* ee.Filter methods (static constructors) */
const EE_FILTER_METHODS = [
  'and',
  'aside',
  'bounds',
  'calendarRange',
  'contains',
  'dateRangeContains',
  'dayOfYear',
  'disjoint',
  'equals',
  'evaluate',
  'getInfo',
  'greaterThan',
  'greaterThanOrEquals',
  'hasType',
  'intersects',
  'isContained',
  'lessThan',
  'lessThanOrEquals',
  'listContains',
  'maxDifference',
  'neq',
  'not',
  'notContains',
  'notEquals',
  'notNull',
  'or',
  'rangeContains',
  'serialize',
  'stringContains',
  'stringEndsWith',
  'stringStartsWith',
  'withinDistance',
];

/* ee.Reducer methods (static constructors and instance methods) */
const EE_REDUCER_METHODS = [
  'allNonZero',
  'and',
  'anyNonZero',
  'aside',
  'centeredCovariance',
  'combine',
  'count',
  'countDistinct',
  'countDistinctNonNull',
  'countEvery',
  'countRuns',
  'covariance',
  'disaggregate',
  'first',
  'firstNonNull',
  'fixedHistogram',
  'forEach',
  'frequencyHistogram',
  'getOutputs',
  'histogram',
  'intervalMean',
  'kendallsCorrelation',
  'kurtosis',
  'last',
  'lastNonNull',
  'linearFit',
  'linearRegression',
  'max',
  'mean',
  'median',
  'min',
  'minMax',
  'mode',
  'or',
  'pearsonsCorrelation',
  'percentile',
  'product',
  'robustLinearRegression',
  'sampleStdDev',
  'sampleVariance',
  'sensSlope',
  'setOutputs',
  'skew',
  'spearmansCorrelation',
  'splitWeights',
  'stdDev',
  'sum',
  'toCollection',
  'unweighted',
  'variance',
];

/* ee.Kernel methods (static constructors) */
const EE_KERNEL_METHODS = [
  'add',
  'chebyshev',
  'circle',
  'compass',
  'cross',
  'diamond',
  'euclidean',
  'fixed',
  'gaussian',
  'inverse',
  'kirsch',
  'laplacian4',
  'laplacian8',
  'manhattanDistance',
  'octagon',
  'plus',
  'prewitt',
  'rectangle',
  'roberts',
  'rotate',
  'serialize',
  'sobel',
  'square',
];

/* ee.Terrain methods */
const EE_TERRAIN_METHODS = [
  'aspect',
  'fillMinima',
  'hillShadow',
  'hillshade',
  'products',
  'slope',
];

/* Common GEE built-in variables / functions (always available in GEE editor) */
const EE_GLOBALS = [
  'ee',
  'Map',
  'print',
  'Export',
  'Chart',
  'ui',
];

/* Map built-in methods */
const EE_MAP_METHODS = [
  'addLayer',
  'centerObject',
  'clear',
  'getBounds',
  'getCenter',
  'getScale',
  'getZoom',
  'layers',
  'onClick',
  'onChangeBounds',
  'onChangeCenter',
  'onChangeZoom',
  'onIdle',
  'remove',
  'setCenter',
  'setControlVisibility',
  'setCursor',
  'setGestureHandling',
  'setLocked',
  'setMaxZoom',
  'setMinZoom',
  'setOptions',
  'setZoom',
  'style',
  'unlockScale',
  'widgets',
];

/* Export methods */
const EE_EXPORT_METHODS = [
  'image',
  'map',
  'table',
  'video',
];

/* Chart methods */
const EE_CHART_METHODS = [
  'array',
  'feature',
  'image',
];

/**
 * Maps a variable name pattern to its likely type and method list.
 * Used to infer method completions from variable names.
 */
const EE_TYPE_PATTERNS = [
  { pattern: /ImageCollection/i, methods: EE_IMAGE_COLLECTION_METHODS },
  { pattern: /FeatureCollection/i, methods: EE_FEATURE_COLLECTION_METHODS },
  { pattern: /image|img|band|raster/i, methods: EE_IMAGE_METHODS },
  { pattern: /feature|feat|poly|point|line/i, methods: EE_FEATURE_METHODS },
  { pattern: /geom|geometry|roi|aoi|region/i, methods: EE_GEOMETRY_METHODS },
  { pattern: /filter/i, methods: EE_FILTER_METHODS },
  { pattern: /reducer/i, methods: EE_REDUCER_METHODS },
  { pattern: /kernel/i, methods: EE_KERNEL_METHODS },
  { pattern: /date/i, methods: EE_DATE_METHODS },
  { pattern: /num|number/i, methods: EE_NUMBER_METHODS },
  { pattern: /str|string/i, methods: EE_STRING_METHODS },
  { pattern: /list|arr/i, methods: EE_LIST_METHODS },
  { pattern: /dict/i, methods: EE_DICTIONARY_METHODS },
];

/**
 * Maps a constructor pattern in source code to a method list.
 * For example, "var x = ee.Image()" -> EE_IMAGE_METHODS
 */
const EE_CONSTRUCTOR_METHODS = [
  { pattern: /ee\.ImageCollection/, methods: EE_IMAGE_COLLECTION_METHODS },
  { pattern: /ee\.FeatureCollection/, methods: EE_FEATURE_COLLECTION_METHODS },
  { pattern: /ee\.Image/, methods: EE_IMAGE_METHODS },
  { pattern: /ee\.Feature/, methods: EE_FEATURE_METHODS },
  { pattern: /ee\.Geometry/, methods: EE_GEOMETRY_METHODS },
  { pattern: /ee\.Filter/, methods: EE_FILTER_METHODS },
  { pattern: /ee\.Reducer/, methods: EE_REDUCER_METHODS },
  { pattern: /ee\.Kernel/, methods: EE_KERNEL_METHODS },
  { pattern: /ee\.Date/, methods: EE_DATE_METHODS },
  { pattern: /ee\.Number/, methods: EE_NUMBER_METHODS },
  { pattern: /ee\.String/, methods: EE_STRING_METHODS },
  { pattern: /ee\.List/, methods: EE_LIST_METHODS },
  { pattern: /ee\.Dictionary/, methods: EE_DICTIONARY_METHODS },
  { pattern: /ee\.Terrain/, methods: EE_TERRAIN_METHODS },
];

/**
 * Known global object method maps.
 */
const EE_KNOWN_GLOBALS = {
  Map: EE_MAP_METHODS,
  Export: EE_EXPORT_METHODS,
  Chart: EE_CHART_METHODS,
};
